# Generated by Django 3.1.7 on 2021-02-25 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Borrower',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('borrower_id', models.IntegerField(default=0, verbose_name='ID заемщика')),
            ],
            options={
                'verbose_name': 'Заемщик',
                'verbose_name_plural': 'Заемщики',
            },
        ),
        migrations.CreateModel(
            name='Lender',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lender_id', models.IntegerField(default=0, verbose_name='ID займодателя')),
            ],
            options={
                'verbose_name': 'Займодатель',
                'verbose_name_plural': 'Займодатели',
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата платежа')),
                ('monthly_payment', models.IntegerField(default=100000, verbose_name='Перевод')),
            ],
            options={
                'verbose_name': 'Платеж',
                'verbose_name_plural': 'Платежи',
            },
        ),
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total', models.IntegerField(default=7000000, verbose_name='Сумма')),
                ('leftover', models.IntegerField(default=700000, verbose_name='Остаток')),
                ('monthly_payment', models.IntegerField(default=100000, verbose_name='Перевод')),
                ('total_payment', models.IntegerField(default=0, verbose_name='Сумма переводов')),
                ('date_score', models.DateTimeField(auto_now_add=True, verbose_name='Дата платежа')),
                ('payment_status', models.CharField(choices=[('оплачен', 'подтвержден'), ('ожидает', 'ожидает подтверждния')], default='ожидает подтверждния', max_length=30, verbose_name='Статус')),
            ],
            options={
                'verbose_name': 'Счет',
                'verbose_name_plural': 'Счета',
            },
        ),
    ]
