# Generated by Django 3.1.7 on 2021-02-22 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='score',
            options={'verbose_name': 'График', 'verbose_name_plural': 'Графики'},
        ),
        migrations.RemoveField(
            model_name='payment',
            name='payment_status',
        ),
        migrations.AddField(
            model_name='score',
            name='monthly_payment',
            field=models.IntegerField(default=100000, verbose_name='Перевод'),
        ),
        migrations.AddField(
            model_name='score',
            name='payment_status',
            field=models.CharField(choices=[('оплачен', 'подтвержден'), ('ожидает', 'ожидает подтверждния')], default='unpaid', max_length=10, verbose_name='Статус'),
        ),
    ]
