# Generated by Django 3.1.7 on 2021-02-21 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0002_auto_20210221_0851'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата платежа')),
                ('status', models.BooleanField(default=False, verbose_name='Статус')),
                ('total', models.IntegerField(default=7000000, verbose_name='Сумма')),
                ('monthly_payment', models.IntegerField(default=100000, verbose_name='Перевод')),
                ('total_payment', models.IntegerField(default=7000000, verbose_name='Общая сумма переводов')),
            ],
            options={
                'verbose_name': 'Платеж',
                'verbose_name_plural': 'Платежи',
            },
        ),
        migrations.DeleteModel(
            name='Graphic',
        ),
    ]
