# Generated by Django 3.1.7 on 2021-02-21 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0003_auto_20210221_0932'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='status',
        ),
        migrations.AddField(
            model_name='payment',
            name='post_type',
            field=models.CharField(choices=[('paid', 'оплачен'), ('unpaid', 'ожидает')], default='unpaid', max_length=6),
        ),
    ]
