# Generated by Django 3.1.7 on 2021-02-23 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0004_users'),
    ]

    operations = [
        migrations.CreateModel(
            name='Borrower',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('borrower', models.IntegerField(default=0, verbose_name='ID заемщика')),
            ],
            options={
                'verbose_name': 'Заемщик',
                'verbose_name_plural': 'Заемщики',
            },
        ),
        migrations.CreateModel(
            name='Lender',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lender', models.IntegerField(default=0, verbose_name='ID займодателя')),
            ],
            options={
                'verbose_name': 'Займодатель',
                'verbose_name_plural': 'Займодатели',
            },
        ),
        migrations.DeleteModel(
            name='Users',
        ),
    ]
