# Generated by Django 3.1.7 on 2021-02-21 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0004_auto_20210221_0942'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='post_type',
        ),
        migrations.AddField(
            model_name='payment',
            name='payment_status',
            field=models.CharField(choices=[('paid', 'оплачен'), ('unpaid', 'ожидает')], default='unpaid', max_length=6, verbose_name='Статус'),
        ),
    ]
