# Generated by Django 3.1.7 on 2021-02-24 05:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0005_auto_20210223_1506'),
    ]

    operations = [
        migrations.RenameField(
            model_name='borrower',
            old_name='borrower',
            new_name='borrower_id',
        ),
        migrations.RenameField(
            model_name='lender',
            old_name='lender',
            new_name='lender_id',
        ),
    ]
