# Generated by Django 3.1.7 on 2021-02-21 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0005_auto_20210221_1232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_status',
            field=models.CharField(choices=[('pd', 'оплачен'), ('unpd', 'ожидает')], default='pd', max_length=4),
        ),
        migrations.AlterField(
            model_name='payment',
            name='total',
            field=models.IntegerField(default=7000000, verbose_name='Остаток'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='total_payment',
            field=models.IntegerField(default=7000000, verbose_name='Сумма переводов'),
        ),
    ]
