# Generated by Django 3.1.7 on 2021-02-21 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0006_auto_20210221_1250'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_status',
            field=models.CharField(choices=[('оплачен', 'оплачен'), ('ожидает', 'ожидает')], default='pd', max_length=10, verbose_name='Статус'),
        ),
    ]
