# Generated by Django 3.1.7 on 2021-02-21 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0008_auto_20210221_1315'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='score',
            name='total_payment',
        ),
        migrations.AddField(
            model_name='payment',
            name='leftover',
            field=models.IntegerField(default=700000, verbose_name='Остаток'),
        ),
        migrations.AddField(
            model_name='payment',
            name='total',
            field=models.IntegerField(default=7000000, verbose_name='Сумма'),
        ),
        migrations.AddField(
            model_name='payment',
            name='total_payment',
            field=models.IntegerField(default=7000000, verbose_name='Сумма переводов'),
        ),
        migrations.AlterField(
            model_name='score',
            name='total',
            field=models.IntegerField(default=7000000, verbose_name='Сумма'),
        ),
    ]
